name: story_visualization_workflow
description: Generate a story and create scene visualizations
defaultProvider: openai
steps:
  - templateUrl: https://github.com/YatchiYa/templates_prompts_qllm/blob/main/templates/a4a411b9-ecdc-47d2-beab-5578a8b27340/94e3b578-a85b-4836-b756-c861f9173858/story-generator.yaml
    provider: openai
    input:
      genre: "{{genre}}"
      theme: "{{theme}}"
      word_count: "{{word_count}}"
      target_audience: "{{target_audience}}"
    output:
      story: generated_story
      story_elements: story_elements

  - templateUrl: https://github.com/YatchiYa/templates_prompts_qllm/blob/main/templates/a4a411b9-ecdc-47d2-beab-5578a8b27340/94e3b578-a85b-4836-b756-c861f9173858/story-up-v.yaml
    provider: openai
    input:
      scene_text: "$generated_story"
      visual_style: "{{visual_style}}"
      atmospheric_mood: "{{atmospheric_mood}}"
    output:
      visualization: scene_visualization
      cinematic_elements: cinematic_notes
